artifact_location: file:c:/Users/isaac/Documents/GitHub/MStar-ImageClassification/runs/mlflow/778902124032829136
creation_time: 1781104523354
experiment_id: '778902124032829136'
last_update_time: 1781104523354
lifecycle_stage: active
name: /Shared/Ultralytics
